# Generated by Django 2.2.12 on 2020-05-24 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('record_sum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('key_content', models.CharField(max_length=200, verbose_name='Key Content')),
                ('description', models.CharField(max_length=1000, verbose_name='Description')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Item')),
            ],
        ),
    ]
