# Generated by Django 2.2.12 on 2020-06-02 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('duration', models.PositiveSmallIntegerField(default=10)),
                ('key_content', models.CharField(max_length=200, verbose_name='Key Content')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.Item')),
            ],
        ),
    ]
