# Generated by Django 2.2.12 on 2020-05-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0004_auto_20200524_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='item',
            name='record_sum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='record',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
    ]
