# Generated by Django 2.2.12 on 2020-06-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0005_auto_20200527_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='duration',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
